name: RecipeViewer
main: xyz.acrylicstyle.recipeViewer.RecipeViewer
version: "1.0"
api-version: "1.15"
depend:
  - TomeitoLib
commands:
  viewrecipe:
    description: "View recipe"
    aliases: ["vr"]
